# Variables %kitName% %playerName%

# give is for the text linked to the obgiveall command
give:
  kitReceived: "Vous avez reçu le kit %kitName% !"
  invalidKit: "&4Le kit %kitName% n'existe pas !"
  rewardsMessage: "/recompense pour récupérer votre récompense."
  givenToEveryone: "Le kit %kitName% a été donné à tous les joueurs !"
  givenToSpecific: "Le kit %kitName% a été donné à %playerName%"
  playerUnfounded: "Le joueur %playerName% n'a jamais joué sur ce serveur !"

# rewards is for the text linked to the recompense command
rewards:
  kitClaimed: "Vous avez obtenu la récompense %kitName%"
  itemsDropped: "&4Certains items ont été drop au sol !"

# kitsGui is for the text to the kitsGui command
kitsGui:
  kitModified: "Le kit %kitName% a été modifié !"
  kitCreated: "Le kit %kitName% a été créé !"
  alreadyExists: "&4Le kit %kitName% existe déjà !"
  spaceInName: "&4Le kit ne peut pas avoir d'espaces dans son nom !"

# Time unite is in minutes!! Integer only!
schedule:
  initialDelay: 0
  time: 15
  saveMessage: "Sauvegarde OBGiveall"