name: OBGiveAll
version: '${project.version}'
main: mathano.mathano.OBGiveAll
api-version: '1.13'
authors: [Mathano]
description: Permits the creation of custom kits intended for give all.
commands:
  kitsgui:
    description: Permits the creation of custom kits.
    usage: /kitsgui
    permission: obgiveall.kitsgui
    permission-message: You do not have permission.